name: Build Template

on:
  workflow_call:
    inputs:
      build_only:
        required: false
        type: boolean
        default: false
    secrets:
      NEXUS_USERNAME:
        required: false
      NEXUS_PASSWORD:
        required: false
      WEBHOOK_RUNNER_SECRET:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup-java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run build.sh
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ./target/speedcubingLib-1.0-SNAPSHOT.jar

    - name: Setup Maven Settings
      if: ${{ !inputs.build_only }}
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>speedcubing-public-projects-release</id>
              <username>${{ secrets.NEXUS_USERNAME }}</username>
              <password>${{ secrets.NEXUS_PASSWORD }}</password>
            </server>
            <server>
              <id>speedcubing-public-projects-snapshot</id>
              <username>${{ secrets.NEXUS_USERNAME }}</username>
              <password>${{ secrets.NEXUS_PASSWORD }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Deploy to Nexus
      if: ${{ !inputs.build_only }}
      run: |
        mvn deploy -B --no-transfer-progress -DskipTests
        
    - name: Trigger Webhook Runner
      if: ${{ !inputs.build_only }}
      run: |
        curl -X POST https://webhook.speedcubing.top/github/speedcubing-top/speedcubinglib/build \
        -H "Authorization: Bearer ${{ secrets.WEBHOOK_RUNNER_SECRET }}"
